<!DOCTYPE html>
<html>
<head lang="en">
	<meta charset="UTF-8">
	<title>Интернет-магазин</title>
	<link rel="stylesheet" href="/assets/bootstrap-3.3.5-dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="/assets/main/css/common.css" />

</head>
<body>
<div class="container">
	<div class="row">
		<div class="pull-right">
			Баланс: <span id="balance"><?php echo $User->balance; ?></span>
		</div>
	</div>
	<div class="row items" id="items">
		<?php if (count($items) == 0): ?>
			<div class="col-xs-12">
				<h3>Товаров не добавлено. Будьте первым!</h3>
			</div>
		<?php else: ?>
			<?php foreach ($items as $Item): ?>
				<div class="item col-xs-4 text-center" data-id="<?php echo $Item->id; ?>">
					<?php echo $Item->title; ?><br/>
					<span class="price"><?php echo $Item->price; ?> руб.</span><br/>
					<?php if ($Item->creatorId != $User->id): ?>
						<button class="btn btn-default buy" disabled="disabled" type="button">Купить</button>
					<?php endif; ?>
				</div>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
	<div class="row pull-right">
		<button class="btn btn-primary" disabled="disabled" type="button" id="create-item">Добавить товар</button>
	</div>
</div>
<script type="text/javascript" src="/assets/socket/socket.io.min.js"></script>
<script type="text/javascript" src="/assets/jquery/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/assets/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script>
<script>
	var phpssid = '<?php echo $User->sess; ?>';
</script>
<script type="text/javascript" src="/assets/main/js/index.js"></script>
<div class="modal fade" id="modal-create-item">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Добавление товара</h4>
			</div>
			<div class="modal-body">
				<form>
					<div class="form-group">
						<label for="title" class="control-label">Название:</label>
						<input type="text" class="form-control" autocomplete="off" id="title">
					</div>
					<div class="form-group">
						<label for="price" class="control-label">Цена:</label>
						<input type="text" class="form-control" autocomplete="off" id="price">
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Отменить</button>
				<button type="button" class="btn btn-primary" id="create-item-save">Добавить товар</button>
			</div>
		</div>
	</div>
</div>
</body>
</html>